### ISSUE TITLE
Decoding SWO stream

### ISSUE THREAD

**Issue by Gasman2014** [koendv/SerialWireOutput#1]
Hi, Thanks for this project.
Sorry for noob question but I am using this with a Black Magic Probe on macOS. I have an example working on a BluePill with SWO_Async data streaming to the second BMP port but I am confused about the formatting. The stream is interspersed with control characters every 4th byte.

```
␃1487␃ [WA␃RNIN␃G] S␃et u␃p wa␃rnin␃g on␃ Cha␃nnel␃ 1 
�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀��␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀�␀␃1487␃ [IN␃FO] ␃Set ␃up i␃nfo ␃on C␃hann␃el 0␂ 

```
This is my gdb init (I have also tried all other monitor traceswo options)

```
target extended-remote $DEBUG_PORT
monitor swdp_scan
attach 1
monitor traceswo 2250000 decode
```

I have also used a J-Link and the J-Link SWO Viewer correctly decodes the stream. Unfortunately I cannot seem to build 'bmtrace' on macOS (and can only get older versions or Orbuculum to build which don't produce any output at all).

Ultimately, I was also hoping to retrieve the ITM data - any clues as to how to achieve that?

This is my test mule.

```
#include <SWOStream.h>
SWOStream s(2250000, SWO_Async, 0);
SWOStream s2(0, SWO_Async, 1);
int n1, n2 = 0;

void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop()
{
  digitalWrite(LED_BUILTIN, HIGH);
  delay(100);
  digitalWrite(LED_BUILTIN, LOW);
  delay(100);
  s.print(n1++);
  s.print(" [INFO] Set up info on Channel 0 \n");
  s2.print(n1);
  s2.print(" [WARNING] Set up warning on Channel 1 \n");
  s.flush();
  s2.flush();
}
```

**Comment by koendv** [comment]
OK. Looks like an *undecoded* swo stream. The control characters are the beginning of a frame, and say what stream the next characters are on. Using the Arduino SerialWireOutput library, you ought to see frames of 4 characters, except the last frame of a print(), which may be shorter.

I've copied your setup, using the bmp image from here: https://github.com/koendv/blackmagic-bluepill 
but I can't reproduce your problem. 
```cat /dev/ttyACM1 > /tmp/log.txt``` gives me the attached log file. This file looks normal to me. The flush() produces '\0' characters to flush the usb buffers; this is ok. 
[log.txt](https://github.com/koendv/SerialWireOutput/files/4948139/log.txt)

orbuculum handles ITM data; but the user interface is austere.

**Comment by koendv** [comment]
Could you try uploading the binary at https://github.com/koendv/blackmagic-bluepill in your black magic probe, and see if this solves the problem?

**Comment by Gasman2014** [comment]
Hi  - thanks for looking at this. Took a little while to sort out my FTDI cable and download your BMP version. 

I don’t get any output at all when my target PB3 is connected to PA10 on the Blue pill BMP (whatever the monitor traceswo  setting). The only output I get is when I connect PB3 to the PA3 serial port - where I get the same output as before i.e undecoded SWO.
I think I may have done the same with my original setup - I had burned the SWLink version of the BMP (this gives easier to remember pin  assignments) onto my blue pill - and I think I may have been looking at the SWO connected directly to the serial port and not via the SWO in pin on the BMP.

I will have a look at the BMP documentation again for some ideas. The target is clearly outputting the SWO stream but the BMP is not decoding it.


John Pateman

**Comment by koendv** [comment]
For clarity: if you connect bmp to your mac, you ought to see *two* serial ports in /dev/tty* . One (labeled $DEBUG_PORT above) is where gdb sends the binary you want to download to the blue pill. The other serial port is where the decoded output appears after you type "monitor traceswo decode".

**Comment by Gasman2014** [comment]
﻿Thanks - yes, I knew about the two ports /dev/ttyusbmodemXXXXXX1 and 3  - the one ending in 3 is always the serial - and lsusb enumerated the device as a BMP.

So my original problem was that I had managed to connect the SWO of my target board directly to the Serial In of the BMP and not to the SWO pin so was seeing the raw data. This was using a blue pill burnt with the SWLink version of the nightly BMP build.

After a couple of power cycles with your different BMP image, it now seems to be working.. Not sure why it didn’t work immediately with the new BMP software but there are quite a few possible things I had done which could have influenced it.  Thank you!!

I will try again with the original BMP firmware - this was a very recent nightly build. FWIW I have used the SWLink Build (and not the STLink ) on my blue pill - this exposes the end pins on the board so you can just use 4 wires straight through - no need to use a breadboard or remember which pins to use. I will have to investigate if I can get SWO working on that too. 

Many thanks for your software and support. I think you can close this issue. 

John Pateman

**Comment by raghur** [comment]
@Gasman2014 I'm also trying with Bluepill flashed with BMP swlink version. Are you connecting PA3@BMP to PB3@(BluePIll target).
