### ISSUE TITLE
Binary data output format

### ISSUE THREAD

**Issue by Gasman2014** [koendv/SerialWireOutput#2]
At present the SWO output is string formatted only. Would it be possible to add a direct binary write format output too?  I was hoping to graph some of the SWO outputs and the graphing system expects actual binary data to be sent over - so say if you were using 8 bit values then each value would be one single byte sent over with the actual value (so 0x00 0x01 0x02. Is it possible to add 8 & 16 bit binary outputs?

**Comment by koendv** [comment]
Yes and no.
SWO can send data 1, 2 or 4 bytes at a time. You can specify what gets sent from your arduino source.  With ch a char and str an array of char:
- if you use write(ch) or write(str, 1) a header byte and a single byte is sent.
- if you use write(str, 2) a header byte and 2 bytes are sent
- if you use write(str, 4) a header byte and 4 bytes are sent

But there is always a header byte sent first. The header byte says how many data bytes follow and what channel the data bytes are in.
