### ISSUE TITLE
STM32F407VG Serial Monitor Not Working

### ISSUE THREAD

**Issue by Sobhit25** [koendv/SerialWireOutput#3]
I tried serial print on my board STM32F407VG, it was blank.
I installed your package and tried, still its blank, but the led blink program executes.

I also tried different baud rates. I want to complete a project but my stm32duino doesn't let me debug it, the serial monitor is blank.

My upload method is stm32cubeprogrammer(SWD). Other are Serial and DFU but they fail to upload. I need a FTDI for that, but I wanted to know if there is a solution in this way(Usind SWD)

**Comment by koendv** [comment]
On Sat, 03 Oct 2020 19:54:56 -0700
Sobhit25 <notifications@github.com> wrote:

> I tried serial print on my board STM32F407VG, it was blank.
> I installed your package and tried, still its blank, but the led
> blink program executes.
> 
> I also tried different baud rates. I want to complete a project but
> my stm32duino doesn't let me debug it, the serial monitor is blank.
> 
> My upload method is stm32cubeprogrammer(SWD). Other are Serial and
> DFU but they fail to upload. I need a FTDI for that, but I wanted to
> know if there is a solution in this way
> 

What debugger probe are you using? 

There are at least three ways to print debugging output:
- SWO Serial Wire Output
- Semihosting
- Segger RTT
but all three need a debugger probe.

**Comment by Sobhit25** [comment]
I am only using USB A TO MINI B. But I have an onboard debugger, STlinkV2

**Comment by Sobhit25** [comment]
If this won't do, could you please explain to me the steps and if any probe required. Please.
ThankYou

**Comment by koendv** [comment]
On Sun, 04 Oct 2020 21:46:42 -0700
Sobhit25 <notifications@github.com> wrote:

> If this won't do, could you please explain to me the steps and if any
> probe required. Please. ThankYou
> 

There are three ways to print debug output:
- SWO
- Semihosting
- Segger RTT

SWO requires that a connection between the SWO output pin of the
target, and the SWO input pin of the on-board ST-Link. Also, you need
to configure the baudrate on in target source and debugger.

Unless you are certain this connection is on your board, I would forget
it.

Segger RTT only works on German "Segger J-Link" debuggers, not on
ST-Link. I would forget it.

Semihosting needs the same connection your ST-Link uses to download
firmware to the board. This ought to work. If you are using arduino,
try the examples in https://github.com/koendv/STM32duino-Semihosting

koen
